name: Publish beta to docker registry

on:
  push:
    branches:
      - main

jobs:

  release:
    strategy:
      matrix:
        node_version: [ 12 ]
        os: [ ubuntu-latest ]

    if: github.repository == 'PasteUs/PasteMeFrontend'
    name: Build with node ${{ matrix.node_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: build and update cdn
        run: |
          GH_TOKEN=${{ secrets.PRIVATE_TOKEN }} bash .github/shell/build_and_update_cdn.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          push: true
          tags: |
            pasteme/frontend:beta
            registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-frontend:beta

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger Webhook
        if: false
        run: |
          curl -X POST "${{ secrets.BETA_WEBHOOK }}frontend"
